defaults:
  - tartanair_pgo_eval
  - _self_

scenes: [abandonedfactory/abandonedfactory/Easy/P011]
frame_end: -1

slam:
  buffer: 4096
  pgo_mode: se3_scale
  pgo_rotation_only: false
  pgo_backend: cuda_eigen
